name: Bug report
description: Report a problem with the updater or wrapper
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Clear description of the problem and what you expected to happen
      placeholder: A clear and concise description of the bug...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps that reproduce the issue
      placeholder: 1) ... 2) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `codex --wrapper-version`
      placeholder: commit=..., version=...
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant output, including ~/logs/codex-wrapper.log if available
      render: shell
