name: Feature request
description: Suggest an improvement for codex-updater or the wrapper shim.
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Include command samples or logging ideas.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any workarounds today?
